server:
  servlet:
    context-path: /micro-consumer
  port: 8081

spring:
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
  application:
    name: micro-consumer

logging:
  level:
    com.yy.micro.producer.rpc: debug

