server:
  port: 8084
  servlet:
    context-path: /micro-openfegin-sentinel

spring:
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
  application:
    name: micro-openfegin-sentinel
  main:
    allow-bean-definition-overriding: true
feign:
  sentinel:
    enabled: true