server:
  servlet:
    context-path: /micro-producer
  port: 8083

spring:
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
  application:
    name: micro-producer
logging:
  level:
    com.yy.micro.producer.rpc: debug

