server:
  port: 8082
  servlet:
    context-path: micro-gateway

spring:
  application:
    name: micro-gateway
  cloud:
    nacos:
      server-addr: 8.136.206.247:8848
    gateway:
      routes: #路由规则
        - id: micro-producer # 路由标识
          uri: lb://micro-producer #转发地址
          predicates: #断言规则，匹配路由
            - Path=/micro-producer/**
        - id: micro-consumer # 路由标识
          uri: lb://micro-consumer #转发地址
          predicates: #断言规则，匹配路由
            - Path=/micro-consumer/**
    sentinel:
      transport:
        dashboard: localhost:8858
#          filters:
#            - StripPrefix=1



